### Site Settings ###
title               : Rob Hallam
description         : >-
                      "Computer Science student at
                      the University of Birmingham. Fascinated by everything
                      tech. Lover of indie/hip hop music and guitarist."
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          :  # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Rob Hallam
#  image             : 
#  behance           : your_username
# dribbble          : your_username
#  email             : username@domain.com #ADD!!! CONTACT EMAIL!
#  facebook          : your_username
  github            : robj3d3
# gitlab            : your_username
# instagram         : your_username
  linkedin          : robert-hallam-277085195
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : robj3d3
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  hackathons:
    order:
      - localhackday19.md
      - hackthemidlands19.md
      - qiskitcss19.md
      - baesystemsctf20.md
      - googlehashcode20.md
      - whatthectf20.md
    output: true
    permalink: /hackathons/:name
  css-socials:
    output: true
    permalink: /css-socials/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "hackathons"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "css-socials"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

# Don't need output true for hackathons as not a separate site for each, just link to it